- repository: autowarefoundation/sync-file-templates
  source-dir: sources
  files:
    - source: .github/dependabot.yaml
    - source: .github/stale.yml
    - source: .github/workflows/cancel-previous-workflows.yaml
    - source: .github/workflows/comment-on-pr.yaml
    - source: .github/workflows/github-release.yaml
    - source: .github/workflows/pre-commit-optional.yaml
    - source: .github/workflows/pre-commit-optional-autoupdate.yaml
    - source: .github/workflows/pre-commit-autoupdate.yaml
    - source: .github/workflows/semantic-pull-request.yaml
    - source: .github/workflows/spell-check-differential.yaml
    - source: .github/workflows/spell-check-daily.yaml
    - source: .github/workflows/sync-files.yaml
    - source: .markdown-link-check.json
    - source: .markdownlint.yaml
    - source: .pre-commit-config-optional.yaml
    - source: .pre-commit-config.yaml
    - source: CODE_OF_CONDUCT.md
    - source: CONTRIBUTING.md
    - source: DISCLAIMER.md
    - source: LICENSE
- repository: autowarefoundation/autoware
  files:
    - source: .github/workflows/pre-commit-ansible.yaml
    - source: .github/workflows/pre-commit-ansible-autoupdate.yaml
    - source: .pre-commit-config-ansible.yaml
    - source: ansible/roles/artifacts/defaults/main.yaml
    - source: ansible/roles/artifacts/meta/main.yaml
    - source: ansible/roles/artifacts/tasks/main.yaml
    - source: ansible/roles/artifacts/README.md
    - source: ansible/roles/docker_engine/defaults/main.yaml
    - source: ansible/roles/docker_engine/meta/main.yaml
    - source: ansible/roles/docker_engine/tasks/main.yaml
    - source: ansible/roles/docker_engine/README.md
    - source: ansible/roles/nvidia_container_toolkit/defaults/main.yaml
    - source: ansible/roles/nvidia_container_toolkit/meta/main.yaml
    - source: ansible/roles/nvidia_container_toolkit/tasks/main.yaml
    - source: ansible/roles/nvidia_container_toolkit/README.md
